### ISSUE TITLE
`sphinx-autogen` ...no module named errors

### ISSUE THREAD

**Issue by robrobbins** [ApeWorX/eip712#8] opened 2021-10-19 14:17 UTC
![image](https://user-images.githubusercontent.com/60326/137928880-0d1148cb-7bf8-4e19-8f3b-75eacbcf997a.png)

tried from root and /docs

**Comment by fubuloubu** [comment] 2023-01-06 04:16
@robrobbins can you share how you arrived at this error?

**Comment by fubuloubu** [comment] 2023-02-17 18:31
Can't reproduce this issue, so closing for now

**Closed by fubuloubu** 2023-02-17 18:31 UTC
